# Generated by Django 4.0.6 on 2022-09-20 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bank", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bankaccount",
            name="currency",
            field=models.CharField(
                choices=[("EUR", "EUR"), ("USD", "USD")], default="EUR", max_length=3
            ),
        ),
        migrations.AlterField(
            model_name="bankaccount",
            name="name",
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
