# Generated by Django 4.0.6 on 2023-07-10 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("bank", "0004_alter_banktransaction_counter_party_iban"),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banktransaction',
            name='counter_party',
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='currency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='utils.currency'),
        ),
        migrations.AddField(
            model_name='banktransaction',
            name='counter_party_IBAN',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='banktransaction',
            name='counter_party_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='name',
            field=models.CharField(max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name="banktransaction",
            name="amount",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="banktransaction",
            name="balance_after",
            field=models.FloatField(),
        ),
    ]
