# Generated by Django 4.0.6 on 2023-07-10 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankaccount',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='bankcategory',
            name='icon',
        ),
    ]
