# Generated by Django 4.0.6 on 2023-07-10 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0001_initial'),
        ('bank', '0002_remove_bankaccount_currency_remove_bankcategory_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='currency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='utils.currency'),
        ),
        migrations.AddField(
            model_name='bankcategory',
            name='icon',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='utils.muiicon'),
        ),
    ]
