# Generated by Django 4.0.6 on 2022-09-22 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_bankaccount_currency_alter_bankaccount_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banktransaction',
            old_name='counter_party',
            new_name='counter_party_name',
        ),
        migrations.AddField(
            model_name='banktransaction',
            name='counter_party_IBAN',
            field=models.TextField(default='name'),
        ),
    ]
