# Generated by Django 4.0.6 on 2023-07-10 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0003_bankaccount_currency_bankcategory_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banktransaction',
            name='id',
        ),
        migrations.AlterField(
            model_name='banktransaction',
            name='serial_number',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='paymentrequest',
            name='amount_paid',
            field=models.FloatField(default=0),
        ),
    ]
