# Generated by Django 4.0.6 on 2022-09-14 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0003_banktransactioncategoryicon_bankaccount_owner_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banktransactioncategory',
            name='icon',
        ),
        migrations.DeleteModel(
            name='BankTransactionCategoryIcon',
        ),
    ]
