# Generated by Django 4.0.6 on 2022-10-14 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bank", "0004_alter_banktransaction_counter_party_iban"),
    ]

    operations = [
        migrations.AlterField(
            model_name="banktransaction",
            name="amount",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="banktransaction",
            name="balance_after",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="banktransaction",
            name="counter_party_IBAN",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="banktransaction",
            name="counter_party_name",
            field=models.TextField(blank=True, null=True),
        ),
    ]
