# Generated by Django 4.0.6 on 2022-09-14 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0001_initial'),
        ('bank', '0004_remove_banktransactioncategory_icon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='banktransactioncategory',
            name='icon',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='utils.muiicon'),
        ),
    ]
