# Generated by Django 4.0.6 on 2022-10-14 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bank", "0005_alter_banktransaction_amount_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bankaccount",
            name="currency",
        ),
    ]
