# Generated by Django 4.0.6 on 2022-10-14 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("utils", "0002_currency"),
        ("bank", "0006_remove_bankaccount_currency"),
    ]

    operations = [
        migrations.AddField(
            model_name="bankaccount",
            name="currency",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="utils.currency",
            ),
        ),
    ]
