# Generated by Django 4.0.6 on 2022-10-17 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0002_currency'),
        ('bank', '0007_bankaccount_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='utils.currency'),
        ),
        migrations.CreateModel(
            name='PaymentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('original_bank_transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.banktransaction')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('original_bank_transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.banktransaction')),
                ('payment_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.paymentrequest')),
            ],
        ),
    ]
