# Generated by Django 4.0.6 on 2022-10-17 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0009_paymentrequest_bank_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentrequest',
            name='bank_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.bankaccount'),
        ),
    ]
