# Generated by Django 4.0.6 on 2022-09-12 14:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bank_portfolio', '0002_alter_bankaccount_iban_alter_bankaccount_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankTransactionCategoryIcon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mui_name', models.CharField(max_length=32)),
            ],
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='BankTransactionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('description', models.TextField(max_length=128)),
                ('icon', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bank_portfolio.banktransactioncategoryicon')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BankTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.IntegerField()),
                ('serial_number', models.IntegerField()),
                ('counter_party', models.TextField()),
                ('balance_after', models.IntegerField()),
                ('description', models.TextField()),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank_portfolio.bankaccount')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bank_portfolio.banktransactioncategory')),
            ],
        ),
    ]
